# --- !Ups

create table "artikelen" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "ean" varchar  not null ,
  "omschrijving" varchar not null,
  "artgroep" varchar not null,
  "prijs" int not null,
  CONSTRAINT eanUniek unique ("ean")
);



# --- !Downs

drop table "artikelen" if exists;
